# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/bzcEdit/vivada/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/bzcEdit/vivada/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/bzcEdit/vivada/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/bzcEdit/vivada/CPU/instr.coe
read_verilog -library xil_defaultlib {
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/defines.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/EXT.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/alu.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/cmp.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/controller.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/forwarding.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/hazarddetection.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/mem.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/mux.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/regfile.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/seg7x16.v
  D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/new/pipeline_CPU.v
}
read_ip -quiet D:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/bzcEdit/vivada/CPU/CPU.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/bzcEdit/vivada/CPU/icf.xdc
set_property used_in_implementation false [get_files D:/bzcEdit/vivada/CPU/icf.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top pipeline_CPU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pipeline_CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pipeline_CPU_utilization_synth.rpt -pb pipeline_CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
